import initSqlJs from "sql.js";
import fs from "node:fs/promises";
import path from "node:path";

const sql = `
CREATE TABLE IF NOT EXISTS "ProductProject" ("id" TEXT NOT NULL PRIMARY KEY,"sourceUrl" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'draft',"productName" TEXT,"category" TEXT,"brand" TEXT,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" DATETIME NOT NULL);
CREATE TABLE IF NOT EXISTS "ProductSource" ("id" TEXT NOT NULL PRIMARY KEY,"productId" TEXT NOT NULL,"url" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'pending',"htmlSnapshot" TEXT,"textSnapshot" TEXT,"metadata" TEXT,"error" TEXT,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" DATETIME NOT NULL,CONSTRAINT "ProductSource_productId_fkey" FOREIGN KEY ("productId") REFERENCES "ProductProject" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "SourceAsset" ("id" TEXT NOT NULL PRIMARY KEY,"productId" TEXT NOT NULL,"kind" TEXT NOT NULL,"role" TEXT NOT NULL DEFAULT 'unknown',"url" TEXT,"localPath" TEXT,"altText" TEXT,"width" INTEGER,"height" INTEGER,"metadata" TEXT,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "SourceAsset_productId_fkey" FOREIGN KEY ("productId") REFERENCES "ProductProject" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "EvidenceItem" ("id" TEXT NOT NULL PRIMARY KEY,"productId" TEXT NOT NULL,"sourceId" TEXT,"assetId" TEXT,"kind" TEXT NOT NULL,"text" TEXT NOT NULL,"selector" TEXT,"url" TEXT,"confidence" REAL NOT NULL DEFAULT 0.7,"metadata" TEXT,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "EvidenceItem_productId_fkey" FOREIGN KEY ("productId") REFERENCES "ProductProject" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "ProductTruthSnapshot" ("id" TEXT NOT NULL PRIMARY KEY,"productId" TEXT NOT NULL,"schemaVersion" TEXT NOT NULL,"payload" TEXT NOT NULL,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ProductTruthSnapshot_productId_fkey" FOREIGN KEY ("productId") REFERENCES "ProductProject" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "Claim" ("id" TEXT NOT NULL PRIMARY KEY,"productId" TEXT NOT NULL,"text" TEXT NOT NULL,"claimType" TEXT NOT NULL,"confidence" REAL NOT NULL,"safe" BOOLEAN NOT NULL DEFAULT false,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Claim_productId_fkey" FOREIGN KEY ("productId") REFERENCES "ProductProject" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "SalesPotentialScore" ("id" TEXT NOT NULL PRIMARY KEY,"productId" TEXT NOT NULL,"score" INTEGER NOT NULL,"grade" TEXT NOT NULL,"breakdown" TEXT NOT NULL,"penalties" TEXT NOT NULL,"rationale" TEXT NOT NULL,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "SalesPotentialScore_productId_fkey" FOREIGN KEY ("productId") REFERENCES "ProductProject" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "CustomerPain" ("id" TEXT NOT NULL PRIMARY KEY,"productId" TEXT NOT NULL,"text" TEXT NOT NULL,"buyingMotive" TEXT NOT NULL,"situation" TEXT,"evidenceIds" TEXT NOT NULL,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "CustomerPain_productId_fkey" FOREIGN KEY ("productId") REFERENCES "ProductProject" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "SalesAngle" ("id" TEXT NOT NULL PRIMARY KEY,"productId" TEXT NOT NULL,"angle" TEXT NOT NULL,"targetCustomer" TEXT NOT NULL,"customerPain" TEXT NOT NULL,"buyingMotive" TEXT NOT NULL,"corePromise" TEXT NOT NULL,"proofStrategy" TEXT NOT NULL,"requiredEvidenceIds" TEXT NOT NULL,"objectionToRemove" TEXT NOT NULL,"riskFlags" TEXT NOT NULL,"score" INTEGER NOT NULL,"scoreBreakdown" TEXT NOT NULL,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "SalesAngle_productId_fkey" FOREIGN KEY ("productId") REFERENCES "ProductProject" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "HookCandidate" ("id" TEXT NOT NULL PRIMARY KEY,"productId" TEXT NOT NULL,"angleId" TEXT,"text" TEXT NOT NULL,"pattern" TEXT NOT NULL,"startsWithProductName" BOOLEAN NOT NULL DEFAULT false,"supportedClaimIds" TEXT NOT NULL,"riskFlags" TEXT NOT NULL,"score" INTEGER NOT NULL,"decision" TEXT NOT NULL,"rejectionReason" TEXT,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "HookCandidate_productId_fkey" FOREIGN KEY ("productId") REFERENCES "ProductProject" ("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "HookCandidate_angleId_fkey" FOREIGN KEY ("angleId") REFERENCES "SalesAngle" ("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "Storyboard" ("id" TEXT NOT NULL PRIMARY KEY,"productId" TEXT NOT NULL,"angleId" TEXT,"hookId" TEXT,"durationSec" INTEGER NOT NULL,"aspectRatio" TEXT NOT NULL DEFAULT '9:16',"payload" TEXT NOT NULL,"cta" TEXT NOT NULL,"missingShots" TEXT NOT NULL,"renderVariant" TEXT NOT NULL,"complianceReportId" TEXT,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Storyboard_productId_fkey" FOREIGN KEY ("productId") REFERENCES "ProductProject" ("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "Storyboard_angleId_fkey" FOREIGN KEY ("angleId") REFERENCES "SalesAngle" ("id") ON DELETE SET NULL ON UPDATE CASCADE,CONSTRAINT "Storyboard_hookId_fkey" FOREIGN KEY ("hookId") REFERENCES "HookCandidate" ("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "ProofScene" ("id" TEXT NOT NULL PRIMARY KEY,"storyboardId" TEXT NOT NULL,"type" TEXT NOT NULL,"orderIndex" INTEGER NOT NULL,"durationSec" INTEGER NOT NULL,"visualPlan" TEXT NOT NULL,"narration" TEXT NOT NULL,"onScreenText" TEXT NOT NULL,"assetIds" TEXT NOT NULL,"evidenceIds" TEXT NOT NULL,"requiresUserShot" BOOLEAN NOT NULL DEFAULT false,"shotRequest" TEXT,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ProofScene_storyboardId_fkey" FOREIGN KEY ("storyboardId") REFERENCES "Storyboard" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "ShotRequest" ("id" TEXT NOT NULL PRIMARY KEY,"productId" TEXT NOT NULL,"storyboardId" TEXT,"description" TEXT NOT NULL,"reason" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'needed',"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" DATETIME NOT NULL,CONSTRAINT "ShotRequest_productId_fkey" FOREIGN KEY ("productId") REFERENCES "ProductProject" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "ComplianceReport" ("id" TEXT NOT NULL PRIMARY KEY,"productId" TEXT NOT NULL,"targetType" TEXT NOT NULL,"targetId" TEXT NOT NULL,"verdict" TEXT NOT NULL,"unsupportedClaims" TEXT NOT NULL,"riskyClaims" TEXT NOT NULL,"fakeReviewDetected" BOOLEAN NOT NULL DEFAULT false,"productNameInFirstTwoSeconds" BOOLEAN NOT NULL DEFAULT false,"ctaBeforeLastFiveSeconds" BOOLEAN NOT NULL DEFAULT false,"missingEvidenceIds" TEXT NOT NULL,"requiredFixes" TEXT NOT NULL,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ComplianceReport_productId_fkey" FOREIGN KEY ("productId") REFERENCES "ProductProject" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "VideoRender" ("id" TEXT NOT NULL PRIMARY KEY,"productId" TEXT NOT NULL,"storyboardId" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'queued',"variant" TEXT NOT NULL,"filePath" TEXT,"thumbnailPath" TEXT,"width" INTEGER NOT NULL DEFAULT 1080,"height" INTEGER NOT NULL DEFAULT 1920,"durationSec" INTEGER NOT NULL,"error" TEXT,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" DATETIME NOT NULL,CONSTRAINT "VideoRender_productId_fkey" FOREIGN KEY ("productId") REFERENCES "ProductProject" ("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "VideoRender_storyboardId_fkey" FOREIGN KEY ("storyboardId") REFERENCES "Storyboard" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "ConversionPackage" ("id" TEXT NOT NULL PRIMARY KEY,"productId" TEXT NOT NULL,"videoRenderIds" TEXT NOT NULL,"payload" TEXT NOT NULL,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ConversionPackage_productId_fkey" FOREIGN KEY ("productId") REFERENCES "ProductProject" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "PerformanceRecord" ("id" TEXT NOT NULL PRIMARY KEY,"productId" TEXT NOT NULL,"videoRenderId" TEXT,"views" INTEGER,"avgViewDuration" REAL,"retentionRate" REAL,"clickThroughRate" REAL,"purchases" INTEGER,"comments" INTEGER,"notes" TEXT,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "PerformanceRecord_productId_fkey" FOREIGN KEY ("productId") REFERENCES "ProductProject" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "ImprovementPlan" ("id" TEXT NOT NULL PRIMARY KEY,"productId" TEXT NOT NULL,"performanceId" TEXT,"payload" TEXT NOT NULL,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ImprovementPlan_productId_fkey" FOREIGN KEY ("productId") REFERENCES "ProductProject" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "PromptRun" ("id" TEXT NOT NULL PRIMARY KEY,"productId" TEXT,"task" TEXT NOT NULL,"model" TEXT NOT NULL,"input" TEXT NOT NULL,"output" TEXT,"schemaVersion" TEXT,"status" TEXT NOT NULL,"error" TEXT,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "PromptRun_productId_fkey" FOREIGN KEY ("productId") REFERENCES "ProductProject" ("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE TABLE IF NOT EXISTS "_ClaimToEvidenceItem" ("A" TEXT NOT NULL,"B" TEXT NOT NULL,CONSTRAINT "_ClaimToEvidenceItem_A_fkey" FOREIGN KEY ("A") REFERENCES "Claim" ("id") ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT "_ClaimToEvidenceItem_B_fkey" FOREIGN KEY ("B") REFERENCES "EvidenceItem" ("id") ON DELETE CASCADE ON UPDATE CASCADE);
CREATE UNIQUE INDEX IF NOT EXISTS "SalesPotentialScore_productId_key" ON "SalesPotentialScore"("productId");
CREATE UNIQUE INDEX IF NOT EXISTS "_ClaimToEvidenceItem_AB_unique" ON "_ClaimToEvidenceItem"("A", "B");
CREATE INDEX IF NOT EXISTS "_ClaimToEvidenceItem_B_index" ON "_ClaimToEvidenceItem"("B");
`;

async function main() {
  const SQL = await initSqlJs();
  const db = new SQL.Database();
  db.run("PRAGMA foreign_keys = ON;");
  db.run(sql);
  const output = db.export();
  const dbPath = path.join(process.cwd(), "prisma", "dev.db");
  await fs.mkdir(path.dirname(dbPath), { recursive: true });
  await fs.writeFile(dbPath, output);
  console.log(`Initialized ${dbPath}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
